/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-102008-gf7c3484b26-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
